# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Pdf Layout

# Model Form Field configuration
form: $/waka/pdfer/models/pdflayout/fields.yaml

# Model Class name
modelClass: Waka\Pdfer\Models\PdfLayout

# Default redirect location
defaultRedirect: waka/pdfer/pdflayouts

# Create page
create:
    title: Create Pdf Layout
    redirect: waka/pdfer/pdflayouts/update/:id
    redirectClose: waka/pdfer/pdflayouts

# Update page
update:
    title: Edit Pdf Layout
    redirect: waka/pdfer/pdflayouts
    redirectClose: waka/pdfer/pdflayouts

# Preview page
preview:
    title: Preview Pdf Layout
