# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: WakaPdf

# Model Class name
modelClass: Waka\Pdfer\Models\WakaPdf
type: email
text_info: "Glissez une valeur dans la zone de saisie"




