# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Document

# Model Class name
modelClass: Waka\Pdfer\Models\WakaPdf
type: pdf
text_info: "Glissez une valeur dans la zone de saisie"


