# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.pdfer::wakapdf.form_name

# Model Form Field configuration
form: $/waka/pdfer/models/wakapdf/fields.yaml

# Model Class name
modelClass: Waka\Pdfer\Models\WakaPdf

# Default redirect location
defaultRedirect: waka/pdfer/wakapdfs/index/wakamails

# Create page
create:
    title: waka.pdfer::wakapdf.create
    redirect: waka/pdfer/wakapdfs/update/:id
    redirectClose: waka/pdfer/wakapdfs
    form: $/waka/pdfer/models/wakapdf/fields_create.yaml

# Update page
update:
    title: waka.pdfer::wakapdf.update
    redirect: waka/pdfer/wakapdfs/index/wakamails
    redirectClose: waka/pdfer/wakapdfs/index/wakamails

# Preview page
preview:
    title: waka.pdfer::wakapdf.preview_name
