# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.pdfer::bloc.form_name

# Model Form Field configuration
form: $/waka/pdfer/models/bloc/fields.yaml

# Model Class name
modelClass: Waka\Pdfer\Models\Bloc

# Default redirect location
defaultRedirect: waka/pdfer/wakapdfs/index/blocs

# Create page
create:
    title: waka.pdfer::bloc.create
    redirect: waka/pdfer/wakapdfs/update/:id
    redirectClose: waka/pdfer/wakapdfs/index/blocs
    form: $/waka/pdfer/models/bloc/fields_create.yaml

# Update page
update:
    title: waka.pdfer::bloc.update
    redirect: waka/pdfer/blocs/index/blocs
    redirectClose: waka/wakapdfs/blocs/index/blocs

# Preview page
preview:
    title: waka.pdfer::bloc.preview_name
